# Rasa NLU konfiguratsioon.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# Vaikeväärtused
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     entity_recognition: False
   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
   - name: FallbackClassifier
     threshold: 0.2
# Lisakomponendid
# Töötajanime hägune tuvastus
   - name: "components.employee_extractor.EmployeeExtractor"
     no_match_threshold: 20
     low_match_threshold: 50
     high_match_threshold: 80
# Kursuse pealkirja hägune tuvastus
   - name: "components.course_extractor.CourseTitleExtractor"
     match_threshold: 90
# Kursuse sündmuse hägune tuvastus
   - name: "components.course_event_extractor.CourseEventExtractor"
     match_threshold: 80
# Ruuminumbri tuvastus
   - name: "components.room_number_extractor.RoomNumberExtractor"

# Rasa Core konfiguratsioon.
# https://rasa.com/docs/rasa/core/policies/
policies:
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 10
     epochs: 100
