# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# Defaults
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     entity_recognition: False
   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
   - name: FallbackClassifier
     threshold: 0.3
# Custom
# Employee extraction using fuzzy matching
   - name: "components.employee_extractor.EmployeeExtractor"
     match_threshold: 55
# Course title extraction using fuzzy matching
   - name: "components.course_extractor.CourseTitleExtractor"
     match_threshold: 80
# Course event extraction using fuzzy matching
   - name: "components.course_event_extractor.CourseEventExtractor"
     match_threshold: 80
# Value extraction using lookup table
#   - name: RegexEntityExtractor
#     case_sensitive: False
#     use_lookup_tables: True
#     use_regexes: False
# Number recognition for room booking
#   - name: "DucklingEntityExtractor"
#     url: "http://localhost:8000"
#     dimensions: ["number"]
#     timezone: "Europe/Tallinn"
#     timeout: 3

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 10
     epochs: 100
   - name: RulePolicy
